services:
  webpack-container:
    container_name: "webpack-container"
    image: node:20.18.1
    volumes:
      - ./app:/app
      - ./package.json:/package.json
      - ./webpack.config.js:/webpack.config.js
      - ./wp-content/themes:/wp-content/themes
    working_dir: /
    command: bash -c "npm install && npm run webpack:prod"
